apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rsshub
resources:
  - namespace.yaml
  - deployment-redis.yaml
  - deployment-browserless.yaml
  - deployment-rsshub.yaml
  - httproute.yaml
  - certificate.yaml
  - secret.yaml
