apiVersion: v1
kind: Secret
metadata:
  name: rsshub-secrets
  namespace: rsshub
type: Opaque
stringData:
  # Replace with your actual Instagram cookie
  IG_COOKIE: "ig_did=122533BC-4B64-4837-B970-905927A4ACB5; csrftoken=IxEma4_X8m5eL1kyfGwLly; sessionid=186130834%3AYTRvCPqFBzOeTr%3A5%3AAYhLvpE0Bf2PbBA-qU5VCobrUmoQsR4vwn3PSTDAjg; ds_user_id=186130834; mid=aJ4cFwAEAAGkeycNhslbrwaTPBGw"
