apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homebridge-tls
  namespace: homebridge
spec:
  secretName: homebridge-tls
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    size: 2048
  dnsNames:
    - homebridge.lan
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
