apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: doppler-redis
  namespace: agent-api
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-redis
            key: dopplerToken
