apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: doppler
  namespace: agent-api
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token
            key: dopplerToken
      nameTransformer: lower-kebab
