apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secrets-db-password
  namespace: n8n
spec:
  secretStoreRef:
    name: doppler-postgresql
    kind: SecretStore
  target:
    name: n8n-secrets
    creationPolicy: CreateOrMerge
  refreshInterval: 1h
  data:
    - secretKey: db-password
      remoteRef:
        key: PASSWORD
