---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secrets
  namespace: n8n
spec:
  encryptedData:
    db-password: AgBVnaDR3jl08B83apdgNqv8nuE1MrjSytCqKWc93JE6mgnjq6IJwQ0ofLaoeGUpvf382VlU236Vo8gNX3yUytxsljDVBfVlqAhhStXvLqMfnPW9ikADXbve2nZsOXwd4haG6kABNW8gBS8Le3HjU/drWzrIIZMEnUTuket8Klh+RUwwYBnM9wT2yT4O8kT5OK8Ey0sY6W7BzHF7zJCNNpw+T8OcsHrTJWBCmKwVkr83RI5RxKEuJRFQrCghkls/TdPtK5S5grO1xhh+EtKGrn85eEZTfq/afMglxPTLtQWIkZKVQoraMDID3njrBEHJjRRPu4YCV4uc8pyKdKYcFNvkylDgfAblo3JkbCudaeQp8jZ17Be346umzJiAxyw5x2T+WN6Fn3GTTbKBM8dGCOXFzdc7MQJSgpDQLlLzDcCXCRmICZzFpsMtXdTmQ9/Jgclk/FQl8owvYpsEKz6uA2DBphwAw5DYeszSKbN52vIuX5ObzovDD6RBO6FM75haiEns3/ETXzTu2dHAK/xCgmiT+G6eQfvrULsXKcSo1HwLqa6GVZ2CmVhgV8m/fU8pkmxc7vCN25ONXl4JaDsIZmKZfBrcUzaPHYuIU3NQQcW0vV9gdGUEW3I5rc7qdqBWQP1TKUDQV0PdR+q/Qi9NR8+GlALvAveYGjtad4UuM5qICaFSoNpSRzsdOk+FLoacgOBkYNM3UPJrJBD4T7nVzeARoIwhjMgD9VWmEKWhhBE03Q==
    encryption-key: AgA2ga9RT8NfzyUy4bBCGtSSgySZnbG7RSL8DNnH98KjK/pEilhUQiqL08xP26YYIXbulayzU+0a2yhNtDSWpB4mW83+Ibrj1a7elsONjQU9ZAZWRs8LhlPA+Z1CnzB22xKawKza4UwKpKPbn3aduG4B08cNHK30zbEITy1PRA4MRpkFLdyxUon+z0kiOUFvI8Gm9cnWzh2b/Cv2qniXWlSZmsBzndXftQfk5IXsM1iRfxfkXQyfDcohcd+pfqaxjn80hLReHAgvEzA/vcLycwlhVDaLjfy6Bgo1LOnfc6vRv8h8kJY2cuK1DVuDzq67479hRcBArKrQ3YWDG35IrkVD+grr5zNBeoDdOb0cl/CfM9ELXcgAuAKbAyBkJizAGasa7pHrLXauNXlz/RMcIblToGgcrMdS5IeZ6ZahxG9j6JoCI9xtV8pHJvxU2E51FLmsCr9qoss45C+8wvND0K0++vnzKI9jXBQ0tQtHdRXdxmke6Hi27S0SfAJY3UkI459FmlMGgZAcJ5tMflYnXikIzaBs/cLE50YgMw+OKQhi8haYBwFcBrUwrGCVZkfN6xjpaskYeZSnTABCfiZLwFfXmgpKtc6UCUw85M6J17k4FuLtnXePMCSlS6cOV99Lzvff7VJs5RaQpzQQWlNUpv86Qw4ZYzTlwzmO3qpLTTwEbLoc1ghDIbiqeQ3AoSger5BHoTAP5Jw6waF7dYJs0+qouHcXTEum4Z404G/hg9cORckfQ9rIYapAdSibSA==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secrets
      namespace: n8n
