apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-r2-backup-secret
  namespace: longhorn-system
spec:
  secretStoreRef:
    name: doppler
    kind: SecretStore
  target:
    name: longhorn-r2-backup-secret
  refreshInterval: 1h
  dataFrom:
    - find:
        name:
          regexp: ".*"
