apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: offsite-backup-daily
  namespace: longhorn-system
spec:
  cron: "0 2 * * *"
  task: backup
  retain: 5
  concurrency: 2
  groups:
    - offsite-backup
  labels: {}
