apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials
  namespace: postgresql
spec:
  secretStoreRef:
    name: doppler
    kind: SecretStore
  target:
    name: postgresql-credentials
  refreshInterval: 1h
  dataFrom:
    - find:
        name:
          regexp: ".*"
