---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-credentials
  namespace: postgresql
spec:
  encryptedData:
    password: AgA+5uzAGeFYePm9vUN6GMBmQ6109wf0DqtU7cPiCGBD1CBv9a6qS/vy+PzXAL0++CMMQRci0ODfn5VXmPBCFCKbDglaKsY3WC02jhxDJHONTyswEyu5aeeVRS/8DRpyTVcY1npzwpvixoVb+SunFxx0dZCO7/LmfJH+tjQCQD1oGxzJuziEiPcb4dO8lk9Mxk0Ud1Spu9R3qRtYjAFh2jo8kwI9Y9LxgoGm+1JtCLAoRrRZSPB7SJDnOJ8MVBiTrZTfp3lYTqBEYsuQPLvU0W64zZ6L6JZHYVSOKJIFKWk1BtCV2r0rSwfYMxwMdOZ7aaWl3tKMbxmSqPjL/kS0tGXHfziMB+Y+Pkv4ZBL9neikqZWDWjwFe9eQyMCzaYk4JSunXcZaCbq8HJHVz7mc1Afu/ayCQX3KGUlc/f3Pk8gDbmc65h7rkzesQpavhP7LAjfM/RK3eHegGxMLfrvYAWwOghDGeQPCslMQvegvUoU9eI7FNm9i58dosPBOE39Wl1c/QTUm8fpN6xLtR/cY9l+h5+m5jxaMWRqMw804DKuxQqDVHMss1b5utyhijjBtoeekVPx+ZlDd9LcQCr0WDdtUeexA/p+cWGfKFKEwduUwI8fzQTCBYOylYGQRnP63M14c3dkcdSe5Kiom12McGXlafccUaexX1qwNqKH7LGeWaiRCxpGv3p9oQ+UVYcHm+H450OlL+mACe2L+iTy+owjHRyB7bGn9DLjSk9iJw7a2LA==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-credentials
      namespace: postgresql
