apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agents-appset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: agents
  source:
    repoURL: https://github.com/joan-grau/k3s-argocd-starter.git
    targetRevision: HEAD
    path: agents
    directory:
      include: agents-appset.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
