apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: redis
  labels:
    recurring-job-group.longhorn.io/agent-data: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
