apiVersion: v1
kind: ResourceQuota
metadata:
  name: redis-quota
  namespace: redis
spec:
  hard:
    requests.cpu: "100m"
    requests.memory: "128Mi"
    limits.cpu: "400m"
    limits.memory: "256Mi"
