---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-credentials
  namespace: redis
spec:
  encryptedData:
    password: AgBklYC6VLvyUOnoL5CHHF1gnBIIPdi/sDel1kb2txsmGqj6Xid3ub/UgCvlp13jViKO8hhqWc6ImsTWNrWym/d6km0ZOT+Lbnc9IKSznXpT79zTmzMpsuPjB/+6DlUm6XxMVoV1Uv89NBXYunJNMFMqUVhpQFVau1nLtpEXQ1A4JpGg8OJ8OCNA8HGdFoM3T8b8wr/AXrOTWsQ31NWvXrXZuAqo/0LLuLe24AXqMdbk+R4VmP4hLODOcdwNWz5IoC4Vy8ztR5kcTNNitzwJ6kZkbJBHUGwvKI96vwErMkLvl1fEKPn7cEXri4or3CBsR3/3SW8iqG6UjQc17utYM1f94NG1vnGq/4ZbQTSZEXMzN3sUaLUw41U/a4KrEvr/gFAHE0WWvclxNX5ZMtXVbCW1XyhGijGhnvWesie9D5e40JEr8RP1ohWZ2ML7v1wwBHczGBAEqyndEWpzColIi6rRCF31icQ1mT66e7mA2ys5p+Hgqd8QgCgEGkHK2IzHgCoc563FWxiVxL4Dyc2PluiI7y6XfXgQsHBFhPMWoQiVnOmrzVkqb/3KxgAtusvXvxJFTyDC4OcfR6ItbAAybG11Sfirjrl3kbqmTON8RS3uEBHtFJYg1Cp+X21TJsmrjaHB82N+JBF+kf4YywcNOFN1N8o5ef12MuvCmCp7oK031799mjKOFS4bJJQK4LORiRF70MLELA+TPNqicAy5N3I7X/4DDCsMbctd3Rp35SPVcA==
  template:
    metadata:
      creationTimestamp: null
      name: redis-credentials
      namespace: redis
